import { streamText } from 'ai';

import {
  ensureProviderConfigured,
  getDefaultProvider,
  getLanguageModel,
  type ProviderId,
} from './provider.js';
import {
  getVideoSourceConfig,
  getVideoSourceConfigByHost,
  isAllowedVideoAuxiliaryHost,
  type VideoSource,
} from './video-analysis-sources.js';

export type { VideoSource };

export type VideoQualityOption = {
  label: string;
  width?: number;
  height?: number;
  fps?: number;
  bitrate?: number;
  mimeType?: string;
};

export type VideoSubtitleTrack = {
  label: string;
  language?: string;
  url?: string;
  isAutoGenerated?: boolean;
  source?: string;
};

export type VideoAnalysisMetadata = {
  source: VideoSource;
  originalUrl: string;
  finalUrl: string;
  title?: string;
  description?: string;
  thumbnailUrl?: string;
  author?: string;
  duration?: string;
  publishedAt?: string;
  qualities: VideoQualityOption[];
  subtitles: VideoSubtitleTrack[];
  transcriptText?: string;
  transcriptSource?: string;
  warnings: string[];
};

type ParsedVideoFields = Omit<VideoAnalysisMetadata, 'source' | 'originalUrl' | 'finalUrl' | 'warnings'> & {
  warnings?: string[];
};

type FetchTextOptions = {
  accept?: string;
  maxBytes?: number;
  timeoutMs?: number;
  isAllowedUrl: (url: URL) => boolean;
};

const DEFAULT_FETCH_TIMEOUT_MS = 20_000;
const MAX_HTML_BYTES = 2_000_000;
const MAX_SUBTITLE_BYTES = 500_000;
const MAX_TRANSCRIPT_CHARS = 12_000;
const MAX_AI_TRANSCRIPT_CHARS = 10_000;
const MAX_AI_DESCRIPTION_CHARS = 2_000;

const htmlEntityMap: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
  '#39': "'",
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function compactWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function decodeHtmlEntities(raw: string): string {
  return raw
    .replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z0-9]+);/g, (match, entity: string) => {
      if (entity.startsWith('#x') || entity.startsWith('#X')) {
        const codePoint = Number.parseInt(entity.slice(2), 16);
        return Number.isNaN(codePoint) ? match : String.fromCodePoint(codePoint);
      }

      if (entity.startsWith('#')) {
        const codePoint = Number.parseInt(entity.slice(1), 10);
        return Number.isNaN(codePoint) ? match : String.fromCodePoint(codePoint);
      }

      return htmlEntityMap[entity] ?? match;
    })
    .replace(/\u00a0/g, ' ');
}

function stripHtml(raw: string): string {
  return compactWhitespace(
    decodeHtmlEntities(
      raw
        .replace(/<script[\s\S]*?<\/script>/gi, ' ')
        .replace(/<style[\s\S]*?<\/style>/gi, ' ')
        .replace(/<[^>]+>/g, ' '),
    ),
  );
}

function firstString(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) {
      return compactWhitespace(decodeHtmlEntities(value));
    }
  }

  return undefined;
}

function firstNumber(...values: unknown[]): number | undefined {
  for (const value of values) {
    if (typeof value === 'number' && Number.isFinite(value)) {
      return value;
    }
    if (typeof value === 'string' && value.trim()) {
      const parsed = Number(value);
      if (Number.isFinite(parsed)) {
        return parsed;
      }
    }
  }

  return undefined;
}

function normalizeMaybeUrl(value: unknown, baseUrl?: string): string | undefined {
  if (typeof value !== 'string' || !value.trim()) {
    return undefined;
  }

  const trimmed = decodeHtmlEntities(value.trim());

  try {
    if (trimmed.startsWith('//')) {
      return new URL(`https:${trimmed}`).toString();
    }
    return new URL(trimmed, baseUrl).toString();
  } catch {
    return undefined;
  }
}

function parseAttributes(raw: string): Record<string, string> {
  const attributes: Record<string, string> = {};
  const attributeRegex = /([:\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))/g;

  for (const match of raw.matchAll(attributeRegex)) {
    const key = match[1]?.toLowerCase();
    const value = match[2] ?? match[3] ?? match[4] ?? '';
    if (key) {
      attributes[key] = decodeHtmlEntities(value);
    }
  }

  return attributes;
}

function getMetaContent(html: string, names: string[]): string | undefined {
  const wanted = new Set(names.map(name => name.toLowerCase()));
  const metaRegex = /<meta\s+([^>]*?)\/?>/gi;

  for (const match of html.matchAll(metaRegex)) {
    const attributes = parseAttributes(match[1] ?? '');
    const key = (attributes.property ?? attributes.name ?? attributes.itemprop ?? '').toLowerCase();
    if (wanted.has(key) && attributes.content?.trim()) {
      return compactWhitespace(decodeHtmlEntities(attributes.content));
    }
  }

  return undefined;
}

function getTitleTag(html: string): string | undefined {
  const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1];
  return title ? stripHtml(title) : undefined;
}

function extractBalancedJson(source: string, startIndex: number): string | null {
  const opener = source[startIndex];
  const closer = opener === '{' ? '}' : opener === '[' ? ']' : '';
  if (!closer) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let quote = '';
  let escaped = false;

  for (let index = startIndex; index < source.length; index += 1) {
    const char = source[index]!;

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === quote) {
        inString = false;
      }
      continue;
    }

    if (char === '"' || char === "'") {
      inString = true;
      quote = char;
      continue;
    }

    if (char === opener) {
      depth += 1;
      continue;
    }

    if (char === closer) {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, index + 1);
      }
    }
  }

  return null;
}

export function extractJsonAfterMarker(html: string, marker: string): unknown | null {
  const markerIndex = html.indexOf(marker);
  if (markerIndex < 0) {
    return null;
  }

  const objectIndex = html.indexOf('{', markerIndex);
  const arrayIndex = html.indexOf('[', markerIndex);
  const candidates = [objectIndex, arrayIndex].filter(index => index >= 0);
  const startIndex = candidates.length > 0 ? Math.min(...candidates) : -1;
  if (startIndex < 0) {
    return null;
  }

  const raw = extractBalancedJson(html, startIndex);
  if (!raw) {
    return null;
  }

  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function getScriptContentById(html: string, id: string): string | undefined {
  const scriptRegex = /<script\s+([^>]*?)>([\s\S]*?)<\/script>/gi;

  for (const match of html.matchAll(scriptRegex)) {
    const attributes = parseAttributes(match[1] ?? '');
    if (attributes.id === id) {
      return decodeHtmlEntities(match[2] ?? '');
    }
  }

  return undefined;
}

function getJsonLdBlocks(html: string): unknown[] {
  const blocks: unknown[] = [];
  const scriptRegex = /<script\s+([^>]*?)>([\s\S]*?)<\/script>/gi;

  for (const match of html.matchAll(scriptRegex)) {
    const attributes = parseAttributes(match[1] ?? '');
    if (!attributes.type?.toLowerCase().includes('application/ld+json')) {
      continue;
    }

    const raw = decodeHtmlEntities(match[2] ?? '').trim();
    if (!raw) {
      continue;
    }

    try {
      blocks.push(JSON.parse(raw));
    } catch {
      // Ignore malformed JSON-LD.
    }
  }

  return blocks;
}

function walkJson(value: unknown, visit: (record: Record<string, unknown>) => void): void {
  if (Array.isArray(value)) {
    for (const item of value) {
      walkJson(item, visit);
    }
    return;
  }

  if (!isRecord(value)) {
    return;
  }

  visit(value);

  for (const child of Object.values(value)) {
    walkJson(child, visit);
  }
}

function findFirstRecord(value: unknown, predicate: (record: Record<string, unknown>) => boolean): Record<string, unknown> | null {
  let found: Record<string, unknown> | null = null;

  walkJson(value, record => {
    if (!found && predicate(record)) {
      found = record;
    }
  });

  return found;
}

function collectRecords(value: unknown, predicate: (record: Record<string, unknown>) => boolean): Record<string, unknown>[] {
  const records: Record<string, unknown>[] = [];

  walkJson(value, record => {
    if (predicate(record)) {
      records.push(record);
    }
  });

  return records;
}

function getVideoObjectFromJsonLd(html: string): Record<string, unknown> | null {
  for (const block of getJsonLdBlocks(html)) {
    const videoObject = findFirstRecord(block, record => {
      const type = record['@type'];
      if (typeof type === 'string') {
        return type.toLowerCase() === 'videoobject';
      }
      if (Array.isArray(type)) {
        return type.some(item => typeof item === 'string' && item.toLowerCase() === 'videoobject');
      }
      return false;
    });

    if (videoObject) {
      return videoObject;
    }
  }

  return null;
}

function getJsonLdAuthorName(videoObject: Record<string, unknown>): string | undefined {
  const author = videoObject.author ?? videoObject.creator;

  if (typeof author === 'string') {
    return firstString(author);
  }

  if (Array.isArray(author)) {
    for (const item of author) {
      if (isRecord(item)) {
        const name = firstString(item.name);
        if (name) {
          return name;
        }
      }
    }
  }

  if (isRecord(author)) {
    return firstString(author.name);
  }

  return undefined;
}

function getThumbnailFromJsonLd(videoObject: Record<string, unknown>, baseUrl: string): string | undefined {
  const thumbnail = videoObject.thumbnailUrl ?? videoObject.thumbnail;

  if (Array.isArray(thumbnail)) {
    return normalizeMaybeUrl(thumbnail[thumbnail.length - 1], baseUrl) ?? normalizeMaybeUrl(thumbnail[0], baseUrl);
  }

  if (isRecord(thumbnail)) {
    return normalizeMaybeUrl(thumbnail.url, baseUrl);
  }

  return normalizeMaybeUrl(thumbnail, baseUrl);
}

function getGenericMetadata(html: string, finalUrl: string): ParsedVideoFields {
  const videoObject = getVideoObjectFromJsonLd(html);
  const title = firstString(
    videoObject?.name,
    getMetaContent(html, ['og:title', 'twitter:title']),
    getTitleTag(html),
  );
  const description = firstString(
    videoObject?.description,
    getMetaContent(html, ['og:description', 'twitter:description', 'description']),
  );
  const thumbnailUrl =
    (videoObject ? getThumbnailFromJsonLd(videoObject, finalUrl) : undefined) ??
    normalizeMaybeUrl(getMetaContent(html, ['og:image', 'twitter:image']), finalUrl);
  const duration = firstString(videoObject?.duration, getMetaContent(html, ['video:duration']));
  const publishedAt = firstString(
    videoObject?.uploadDate,
    videoObject?.datePublished,
    getMetaContent(html, ['article:published_time', 'date']),
  );

  return {
    title,
    description,
    thumbnailUrl,
    author: videoObject ? getJsonLdAuthorName(videoObject) : undefined,
    duration,
    publishedAt,
    qualities: [],
    subtitles: [],
  };
}

function secondsToDuration(value: unknown): string | undefined {
  const seconds = firstNumber(value);
  if (seconds === undefined) {
    return undefined;
  }

  const totalSeconds = Math.max(0, Math.round(seconds));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const rest = totalSeconds % 60;

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, '0')}:${String(rest).padStart(2, '0')}`;
  }

  return `${minutes}:${String(rest).padStart(2, '0')}`;
}

function unixSecondsToIso(value: unknown): string | undefined {
  const seconds = firstNumber(value);
  if (seconds === undefined || seconds <= 0) {
    return undefined;
  }

  return new Date(seconds * 1000).toISOString();
}

function getRendererText(value: unknown): string | undefined {
  if (typeof value === 'string') {
    return firstString(value);
  }

  if (!isRecord(value)) {
    return undefined;
  }

  const simpleText = firstString(value.simpleText);
  if (simpleText) {
    return simpleText;
  }

  const runs = value.runs;
  if (Array.isArray(runs)) {
    return firstString(
      runs
        .map(run => (isRecord(run) && typeof run.text === 'string' ? run.text : ''))
        .join(''),
    );
  }

  return undefined;
}

function getLargestYoutubeThumbnail(videoDetails: Record<string, unknown>, finalUrl: string): string | undefined {
  const thumbnail = videoDetails.thumbnail;
  const thumbnails = isRecord(thumbnail) && Array.isArray(thumbnail.thumbnails) ? thumbnail.thumbnails : [];
  const normalized = thumbnails
    .filter(isRecord)
    .map(item => ({
      url: normalizeMaybeUrl(item.url, finalUrl),
      width: firstNumber(item.width) ?? 0,
    }))
    .filter((item): item is { url: string; width: number } => Boolean(item.url))
    .sort((a, b) => b.width - a.width);

  return normalized[0]?.url;
}

function normalizeQuality(input: VideoQualityOption): VideoQualityOption | null {
  const label = compactWhitespace(input.label);
  if (!label) {
    return null;
  }

  return {
    label,
    ...(input.width !== undefined ? { width: input.width } : {}),
    ...(input.height !== undefined ? { height: input.height } : {}),
    ...(input.fps !== undefined ? { fps: input.fps } : {}),
    ...(input.bitrate !== undefined ? { bitrate: input.bitrate } : {}),
    ...(input.mimeType ? { mimeType: input.mimeType } : {}),
  };
}

function dedupeQualities(qualities: VideoQualityOption[]): VideoQualityOption[] {
  const map = new Map<string, VideoQualityOption>();

  for (const quality of qualities) {
    const normalized = normalizeQuality(quality);
    if (!normalized) {
      continue;
    }

    const key = `${normalized.label}|${normalized.width ?? ''}|${normalized.height ?? ''}|${normalized.mimeType ?? ''}`;
    if (!map.has(key)) {
      map.set(key, normalized);
    }
  }

  return [...map.values()].slice(0, 24);
}

function dedupeSubtitles(subtitles: VideoSubtitleTrack[]): VideoSubtitleTrack[] {
  const map = new Map<string, VideoSubtitleTrack>();

  for (const subtitle of subtitles) {
    const label = compactWhitespace(subtitle.label);
    if (!label) {
      continue;
    }

    const normalized: VideoSubtitleTrack = {
      label,
      ...(subtitle.language ? { language: compactWhitespace(subtitle.language) } : {}),
      ...(subtitle.url ? { url: subtitle.url } : {}),
      ...(subtitle.isAutoGenerated !== undefined ? { isAutoGenerated: subtitle.isAutoGenerated } : {}),
      ...(subtitle.source ? { source: subtitle.source } : {}),
    };
    const key = `${normalized.label}|${normalized.language ?? ''}|${normalized.url ?? ''}`;
    if (!map.has(key)) {
      map.set(key, normalized);
    }
  }

  return [...map.values()].slice(0, 20);
}

function parseYoutubePage(html: string, finalUrl: string): ParsedVideoFields {
  const generic = getGenericMetadata(html, finalUrl);
  const player = extractJsonAfterMarker(html, 'ytInitialPlayerResponse');

  if (!isRecord(player)) {
    return generic;
  }

  const videoDetails = isRecord(player.videoDetails) ? player.videoDetails : {};
  const streamingData = isRecord(player.streamingData) ? player.streamingData : {};
  const formatRecords = [
    ...(Array.isArray(streamingData.formats) ? streamingData.formats : []),
    ...(Array.isArray(streamingData.adaptiveFormats) ? streamingData.adaptiveFormats : []),
  ].filter(isRecord);
  const qualities = dedupeQualities(
    formatRecords.map(format => {
      const height = firstNumber(format.height);
      const width = firstNumber(format.width);
      return {
        label: firstString(format.qualityLabel, format.quality, height ? `${height}p` : undefined) ?? '',
        width,
        height,
        fps: firstNumber(format.fps),
        bitrate: firstNumber(format.bitrate),
        mimeType: firstString(format.mimeType),
      };
    }),
  );

  const captions = isRecord(player.captions) ? player.captions : {};
  const trackList = isRecord(captions.playerCaptionsTracklistRenderer)
    ? captions.playerCaptionsTracklistRenderer
    : {};
  const captionTracks = Array.isArray(trackList.captionTracks) ? trackList.captionTracks.filter(isRecord) : [];
  const subtitles = dedupeSubtitles(
    captionTracks.map(track => ({
      label: getRendererText(track.name) ?? firstString(track.languageCode) ?? '字幕',
      language: firstString(track.languageCode),
      url: normalizeMaybeUrl(track.baseUrl, finalUrl),
      isAutoGenerated: track.kind === 'asr',
      source: 'youtube-captions',
    })),
  );

  return {
    ...generic,
    title: firstString(videoDetails.title, generic.title),
    description: firstString(videoDetails.shortDescription, generic.description),
    thumbnailUrl: getLargestYoutubeThumbnail(videoDetails, finalUrl) ?? generic.thumbnailUrl,
    author: firstString(videoDetails.author, generic.author),
    duration: secondsToDuration(videoDetails.lengthSeconds) ?? generic.duration,
    publishedAt: generic.publishedAt,
    qualities: qualities.length > 0 ? qualities : generic.qualities,
    subtitles: subtitles.length > 0 ? subtitles : generic.subtitles,
  };
}

function parseBilibiliSubtitleTracks(state: Record<string, unknown>, finalUrl: string): VideoSubtitleTrack[] {
  const tracks: VideoSubtitleTrack[] = [];
  const videoData = isRecord(state.videoData) ? state.videoData : {};
  const subtitle = isRecord(videoData.subtitle) ? videoData.subtitle : isRecord(state.subtitle) ? state.subtitle : {};
  const list = Array.isArray(subtitle.list) ? subtitle.list : [];

  for (const item of list.filter(isRecord)) {
    const url = normalizeMaybeUrl(item.subtitle_url ?? item.url, finalUrl);
    tracks.push({
      label: firstString(item.lan_doc, item.lan, item.label) ?? '字幕',
      language: firstString(item.lan),
      url,
      source: 'bilibili-subtitle',
    });
  }

  return tracks;
}

function parseBilibiliQualities(playinfo: unknown): VideoQualityOption[] {
  if (!isRecord(playinfo)) {
    return [];
  }

  const data = isRecord(playinfo.data) ? playinfo.data : playinfo;
  const supportFormats = Array.isArray(data.support_formats) ? data.support_formats.filter(isRecord) : [];
  const supportQualities = supportFormats.map(format => ({
    label: firstString(format.new_description, format.display_desc, format.description, format.quality) ?? '',
  }));

  const dash = isRecord(data.dash) ? data.dash : {};
  const dashVideos = Array.isArray(dash.video) ? dash.video.filter(isRecord) : [];
  const dashQualities = dashVideos.map(video => {
    const height = firstNumber(video.height);
    return {
      label: firstString(video.id, height ? `${height}p` : undefined) ?? '',
      width: firstNumber(video.width),
      height,
      fps: firstNumber(video.frameRate, video.frame_rate),
      bitrate: firstNumber(video.bandwidth),
      mimeType: firstString(video.mimeType, video.mime_type, video.codecs),
    };
  });

  const acceptDescriptions = Array.isArray(data.accept_description) ? data.accept_description : [];
  const acceptQualities = acceptDescriptions.map(item => ({
    label: firstString(item) ?? '',
  }));

  return dedupeQualities([...supportQualities, ...dashQualities, ...acceptQualities]);
}

function parseBilibiliPage(html: string, finalUrl: string): ParsedVideoFields {
  const generic = getGenericMetadata(html, finalUrl);
  const state = extractJsonAfterMarker(html, '__INITIAL_STATE__');
  const playinfo = extractJsonAfterMarker(html, '__playinfo__');

  if (!isRecord(state)) {
    return {
      ...generic,
      qualities: parseBilibiliQualities(playinfo),
    };
  }

  const videoData = isRecord(state.videoData) ? state.videoData : {};
  const owner = isRecord(videoData.owner) ? videoData.owner : {};
  const qualities = parseBilibiliQualities(playinfo);
  const subtitles = parseBilibiliSubtitleTracks(state, finalUrl);

  return {
    ...generic,
    title: firstString(videoData.title, generic.title),
    description: firstString(videoData.desc, generic.description),
    thumbnailUrl: normalizeMaybeUrl(videoData.pic, finalUrl) ?? generic.thumbnailUrl,
    author: firstString(owner.name, generic.author),
    duration: secondsToDuration(videoData.duration) ?? generic.duration,
    publishedAt: unixSecondsToIso(videoData.pubdate) ?? generic.publishedAt,
    qualities: qualities.length > 0 ? qualities : generic.qualities,
    subtitles: subtitles.length > 0 ? subtitles : generic.subtitles,
  };
}

function parseDouyinHydration(html: string): unknown | null {
  const renderData = getScriptContentById(html, 'RENDER_DATA');
  if (renderData) {
    try {
      return JSON.parse(decodeURIComponent(renderData));
    } catch {
      try {
        return JSON.parse(renderData);
      } catch {
        // Fall through to router data.
      }
    }
  }

  return extractJsonAfterMarker(html, 'window._ROUTER_DATA');
}

function getFirstUrlFromList(value: unknown, baseUrl: string): string | undefined {
  if (Array.isArray(value)) {
    for (const item of value) {
      const url = normalizeMaybeUrl(item, baseUrl);
      if (url) {
        return url;
      }
    }
  }

  return normalizeMaybeUrl(value, baseUrl);
}

function getDouyinImageFromAddress(value: unknown, finalUrl: string): string | undefined {
  if (!isRecord(value)) {
    return normalizeMaybeUrl(value, finalUrl);
  }

  return getFirstUrlFromList(value.url_list, finalUrl) ?? normalizeMaybeUrl(value.uri, finalUrl);
}

function parseDouyinSubtitles(video: Record<string, unknown>, finalUrl: string): VideoSubtitleTrack[] {
  const candidates = [video.subtitle_infos, video.caption_infos, video.subtitles];
  const tracks: VideoSubtitleTrack[] = [];

  for (const candidate of candidates) {
    if (!Array.isArray(candidate)) {
      continue;
    }

    for (const item of candidate.filter(isRecord)) {
      tracks.push({
        label: firstString(item.language, item.lang, item.name) ?? '字幕',
        language: firstString(item.language, item.lang),
        url: normalizeMaybeUrl(item.url, finalUrl) ?? getFirstUrlFromList(item.url_list, finalUrl),
        source: 'douyin-subtitle',
      });
    }
  }

  return dedupeSubtitles(tracks);
}

function parseDouyinQualities(video: Record<string, unknown>): VideoQualityOption[] {
  const bitRates = Array.isArray(video.bit_rate) ? video.bit_rate.filter(isRecord) : [];

  return dedupeQualities(
    bitRates.map(item => {
      const playAddress = isRecord(item.play_addr) ? item.play_addr : {};
      const height = firstNumber(item.height, playAddress.height);
      return {
        label: firstString(item.gear_name, item.quality_type, height ? `${height}p` : undefined) ?? '',
        width: firstNumber(item.width, playAddress.width),
        height,
        bitrate: firstNumber(item.bit_rate),
      };
    }),
  );
}

function parseDouyinPage(html: string, finalUrl: string): ParsedVideoFields {
  const generic = getGenericMetadata(html, finalUrl);
  const hydration = parseDouyinHydration(html);
  const aweme = findFirstRecord(hydration, record => typeof record.desc === 'string' && isRecord(record.video));

  if (!aweme) {
    return generic;
  }

  const video = isRecord(aweme.video) ? aweme.video : {};
  const author = isRecord(aweme.author) ? aweme.author : {};
  const cover = video.cover ?? video.origin_cover ?? video.dynamic_cover;

  return {
    ...generic,
    title: firstString(aweme.desc, generic.title),
    description: firstString(aweme.desc, generic.description),
    thumbnailUrl: getDouyinImageFromAddress(cover, finalUrl) ?? generic.thumbnailUrl,
    author: firstString(author.nickname, generic.author),
    duration: secondsToDuration(firstNumber(video.duration) !== undefined ? Number(video.duration) / 1000 : undefined) ?? generic.duration,
    publishedAt: unixSecondsToIso(aweme.create_time) ?? generic.publishedAt,
    qualities: parseDouyinQualities(video),
    subtitles: parseDouyinSubtitles(video, finalUrl),
  };
}

export function getVideoSourceFromUrl(rawUrl: string): VideoSource | null {
  try {
    const host = new URL(rawUrl).hostname.toLowerCase();
    return getVideoSourceConfigByHost(host)?.id ?? null;
  } catch {
    return null;
  }
}

export function isAllowedVideoPageUrl(rawUrl: string): boolean {
  try {
    const parsed = new URL(rawUrl);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      return false;
    }

    return getVideoSourceFromUrl(parsed.toString()) !== null;
  } catch {
    return false;
  }
}

function isAllowedAuxiliaryUrl(source: VideoSource, parsed: URL): boolean {
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    return false;
  }

  const host = parsed.hostname.toLowerCase();
  return isAllowedVideoAuxiliaryHost(source, host);
}

function getSourceLabel(source: VideoSource | null): string {
  return source ? getVideoSourceConfig(source).label : '目标平台';
}

function getSourceFromMaybeUrl(rawUrl: string): VideoSource | null {
  try {
    return getVideoSourceFromUrl(new URL(rawUrl).toString());
  } catch {
    return null;
  }
}

function getErrorCauseCode(error: unknown): string | undefined {
  if (!isRecord(error)) {
    return undefined;
  }

  const cause = error.cause;
  if (!isRecord(cause)) {
    return undefined;
  }

  return typeof cause.code === 'string' ? cause.code : undefined;
}

export function describeBlockedVideoResponse(rawUrl: string, status: number, statusText: string): string {
  const sourceLabel = getSourceLabel(getSourceFromMaybeUrl(rawUrl));
  const statusLabel = `${status}${statusText ? ` ${statusText}` : ''}`;

  if (status === 401 || status === 403) {
    return `${sourceLabel} 拒绝了本次服务器抓取请求（${statusLabel}）。这通常表示视频页面需要登录、存在地区/年龄限制，或平台风控拒绝了服务器访问；当前功能不会绕过这些限制。`;
  }

  if (status === 429) {
    return `${sourceLabel} 对本次服务器抓取进行了限流（${statusLabel}）。请稍后重试，或更换一个公开视频链接。`;
  }

  if (status === 451) {
    return `${sourceLabel} 因地区或法律限制拒绝返回该视频页面（${statusLabel}）。`;
  }

  if (status === 404 || status === 410) {
    return `${sourceLabel} 返回视频不存在或已不可访问（${statusLabel}）。请确认链接仍然公开有效。`;
  }

  return `${sourceLabel} 页面请求失败（${statusLabel}）。请确认链接公开可访问，且当前网络可以访问该平台。`;
}

export function describeVideoFetchFailure(rawUrl: string, error: unknown): string {
  const sourceLabel = getSourceLabel(getSourceFromMaybeUrl(rawUrl));
  const code = getErrorCauseCode(error);

  if (code === 'UND_ERR_CONNECT_TIMEOUT' || code === 'ETIMEDOUT') {
    return `无法连接到 ${sourceLabel}：连接超时。当前服务器网络可能无法访问该平台，或平台拒绝了来自服务器环境的连接。`;
  }

  if (code === 'ECONNRESET') {
    return `无法连接到 ${sourceLabel}：连接被远端重置。平台可能拒绝了服务器抓取请求。`;
  }

  if (code === 'ENOTFOUND' || code === 'EAI_AGAIN') {
    return `无法解析 ${sourceLabel} 域名。请检查当前服务器网络或 DNS 配置。`;
  }

  if (error instanceof Error && error.message === 'fetch failed') {
    return `无法访问 ${sourceLabel} 视频页面：底层网络请求失败。当前服务器网络可能被平台阻断，或无法直连该平台。`;
  }

  return error instanceof Error ? error.message : `无法访问 ${sourceLabel} 视频页面。`;
}

export function detectVideoAccessBlock(html: string, finalUrl: string): string | null {
  const sourceLabel = getSourceLabel(getSourceFromMaybeUrl(finalUrl));
  const normalized = html.toLowerCase();

  if (
    normalized.includes('before you continue to youtube') ||
    normalized.includes('our systems have detected unusual traffic') ||
    normalized.includes('sign in to confirm') ||
    normalized.includes('this video may be inappropriate') ||
    normalized.includes('this video is private')
  ) {
    return `${sourceLabel} 返回了登录、验证码、年龄限制或风控页面，无法解析公开视频信息。`;
  }

  if (
    normalized.includes('访问过于频繁') ||
    normalized.includes('访问被拒绝') ||
    normalized.includes('请先登录') ||
    normalized.includes('验证码')
  ) {
    return `${sourceLabel} 返回了登录、验证码或风控页面，无法解析公开视频信息。`;
  }

  return null;
}

async function readResponseTextWithLimit(response: Response, maxBytes: number): Promise<string> {
  const reader = response.body?.getReader();
  if (!reader) {
    return await response.text();
  }

  const chunks: Uint8Array[] = [];
  let size = 0;

  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    if (!value) {
      continue;
    }

    size += value.byteLength;
    if (size > maxBytes) {
      await reader.cancel();
      throw new Error('页面内容过大，已停止读取。');
    }

    chunks.push(value);
  }

  return new TextDecoder().decode(Buffer.concat(chunks));
}

async function fetchTextWithRedirects(rawUrl: string, options: FetchTextOptions): Promise<{ finalUrl: string; text: string }> {
  let currentUrl: URL;
  try {
    currentUrl = new URL(rawUrl);
  } catch {
    throw new Error('请输入有效的视频页面地址。');
  }

  if (!options.isAllowedUrl(currentUrl)) {
    throw new Error('当前仅支持 YouTube、bilibili、douyin 等白名单视频网站。');
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), options.timeoutMs ?? DEFAULT_FETCH_TIMEOUT_MS);
  const maxBytes = options.maxBytes ?? MAX_HTML_BYTES;

  try {
    for (let redirects = 0; redirects <= 5; redirects += 1) {
      const response = await fetch(currentUrl, {
        redirect: 'manual',
        signal: controller.signal,
        headers: {
          'User-Agent':
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125 Safari/537.36 ai-sdk-learn/1.0',
          Accept: options.accept ?? 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
      });

      if (response.status >= 300 && response.status < 400) {
        const location = response.headers.get('location');
        if (!location) {
          throw new Error('视频页面发生重定向，但未返回目标地址。');
        }

        currentUrl = new URL(location, currentUrl);
        if (!options.isAllowedUrl(currentUrl)) {
          throw new Error('视频页面重定向到了非白名单站点，已拒绝继续访问。');
        }
        continue;
      }

      if (!response.ok) {
        throw new Error(describeBlockedVideoResponse(currentUrl.toString(), response.status, response.statusText));
      }

      if (!options.isAllowedUrl(new URL(response.url || currentUrl.toString()))) {
        throw new Error('视频页面最终地址不在白名单内，已拒绝解析。');
      }

      const finalUrl = response.url || currentUrl.toString();
      const text = await readResponseTextWithLimit(response, maxBytes);
      const blockedReason = detectVideoAccessBlock(text, finalUrl);
      if (blockedReason) {
        throw new Error(blockedReason);
      }

      return {
        finalUrl,
        text,
      };
    }

    throw new Error('视频页面重定向次数过多，已停止解析。');
  } catch (error) {
    if (error instanceof Error && error.name === 'AbortError') {
      throw new Error('视频页面请求超时，请稍后重试。');
    }
    if (error instanceof Error && error.message === 'fetch failed') {
      throw new Error(describeVideoFetchFailure(currentUrl.toString(), error));
    }
    throw error;
  } finally {
    clearTimeout(timer);
  }
}

function truncateTranscript(rawText: string, warnings: string[]): string {
  const normalized = compactWhitespace(rawText);
  if (normalized.length <= MAX_TRANSCRIPT_CHARS) {
    return normalized;
  }

  warnings.push(`字幕内容较长，已截断为前 ${MAX_TRANSCRIPT_CHARS} 个字符。`);
  return normalized.slice(0, MAX_TRANSCRIPT_CHARS);
}

function parseSubtitleText(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) {
    return '';
  }

  try {
    const parsed = JSON.parse(trimmed) as unknown;
    const body = isRecord(parsed) && Array.isArray(parsed.body) ? parsed.body : Array.isArray(parsed) ? parsed : [];
    const lines = body
      .filter(isRecord)
      .map(item => firstString(item.content, item.text, item.words))
      .filter((line): line is string => Boolean(line));

    if (lines.length > 0) {
      return compactWhitespace(lines.join('\n'));
    }
  } catch {
    // Not JSON; fall through to XML/VTT/plain text parsing.
  }

  if (trimmed.includes('<text')) {
    return compactWhitespace(
      [...trimmed.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/gi)]
        .map(match => stripHtml(match[1] ?? ''))
        .filter(Boolean)
        .join('\n'),
    );
  }

  return compactWhitespace(
    decodeHtmlEntities(trimmed)
      .replace(/^WEBVTT[\s\S]*?\n/i, '')
      .replace(/^\d+\s*$/gm, '')
      .replace(/\d{2}:\d{2}:\d{2}[.,]\d{3}\s+-->\s+\d{2}:\d{2}:\d{2}[.,]\d{3}.*$/gm, '')
      .replace(/<[^>]+>/g, ' '),
  );
}

async function fetchTranscriptText(
  source: VideoSource,
  subtitles: VideoSubtitleTrack[],
  warnings: string[],
): Promise<{ transcriptText?: string; transcriptSource?: string }> {
  const track = subtitles.find(item => item.url);
  if (!track?.url) {
    return {};
  }

  try {
    const url = new URL(track.url);
    if (!isAllowedAuxiliaryUrl(source, url)) {
      warnings.push('发现字幕地址，但字幕地址不属于当前平台可信域名，已跳过读取。');
      return {};
    }

    const result = await fetchTextWithRedirects(url.toString(), {
      accept: 'application/json,text/vtt,application/xml,text/xml,text/plain,*/*;q=0.8',
      maxBytes: MAX_SUBTITLE_BYTES,
      isAllowedUrl: candidate => isAllowedAuxiliaryUrl(source, candidate),
    });
    const text = parseSubtitleText(result.text);

    if (!text) {
      warnings.push('发现公开字幕轨道，但字幕内容为空或无法解析。');
      return {};
    }

    return {
      transcriptText: truncateTranscript(text, warnings),
      transcriptSource: track.label,
    };
  } catch {
    warnings.push('发现公开字幕轨道，但读取字幕内容失败。');
    return {};
  }
}

export function parseVideoPageMetadata(options: {
  html: string;
  originalUrl: string;
  finalUrl: string;
}): VideoAnalysisMetadata {
  const source = getVideoSourceFromUrl(options.finalUrl);
  if (!source) {
    throw new Error('当前仅支持 YouTube、bilibili、douyin 等白名单视频网站。');
  }

  const parsed =
    source === 'youtube'
      ? parseYoutubePage(options.html, options.finalUrl)
      : source === 'bilibili'
        ? parseBilibiliPage(options.html, options.finalUrl)
        : parseDouyinPage(options.html, options.finalUrl);
  const warnings = [...(parsed.warnings ?? [])];
  const qualities = dedupeQualities(parsed.qualities ?? []);
  const subtitles = dedupeSubtitles(parsed.subtitles ?? []);

  if (!parsed.title) {
    warnings.push('未能从页面中解析到视频标题。');
  }
  if (qualities.length === 0) {
    warnings.push('未能从公开页面中解析到清晰度信息。');
  }
  if (subtitles.length === 0) {
    warnings.push('未发现公开字幕轨道，AI 分析将只基于页面元信息。');
  }

  return {
    source,
    originalUrl: options.originalUrl,
    finalUrl: options.finalUrl,
    ...(parsed.title ? { title: parsed.title } : {}),
    ...(parsed.description ? { description: parsed.description } : {}),
    ...(parsed.thumbnailUrl ? { thumbnailUrl: parsed.thumbnailUrl } : {}),
    ...(parsed.author ? { author: parsed.author } : {}),
    ...(parsed.duration ? { duration: parsed.duration } : {}),
    ...(parsed.publishedAt ? { publishedAt: parsed.publishedAt } : {}),
    qualities,
    subtitles,
    warnings,
  };
}

export async function analyzeVideoUrl(rawUrl: string): Promise<VideoAnalysisMetadata> {
  const fetched = await fetchTextWithRedirects(rawUrl, {
    maxBytes: MAX_HTML_BYTES,
    isAllowedUrl: url => isAllowedVideoPageUrl(url.toString()),
  });
  const metadata = parseVideoPageMetadata({
    html: fetched.text,
    originalUrl: rawUrl,
    finalUrl: fetched.finalUrl,
  });
  const warnings = [...metadata.warnings];
  const transcript = await fetchTranscriptText(metadata.source, metadata.subtitles, warnings);

  return {
    ...metadata,
    ...transcript,
    warnings,
  };
}

function formatQualityList(qualities: VideoQualityOption[]): string {
  if (qualities.length === 0) {
    return '无公开清晰度信息';
  }

  return qualities
    .slice(0, 12)
    .map(quality => {
      const details = [
        quality.width && quality.height ? `${quality.width}x${quality.height}` : null,
        quality.fps ? `${quality.fps}fps` : null,
        quality.mimeType,
      ].filter(Boolean);
      return `- ${quality.label}${details.length > 0 ? `（${details.join('，')}）` : ''}`;
    })
    .join('\n');
}

function formatSubtitleList(subtitles: VideoSubtitleTrack[]): string {
  if (subtitles.length === 0) {
    return '无公开字幕轨道';
  }

  return subtitles
    .map(subtitle => `- ${subtitle.label}${subtitle.language ? `（${subtitle.language}）` : ''}${subtitle.isAutoGenerated ? '，自动字幕' : ''}`)
    .join('\n');
}

export function buildVideoAnalysisPrompt(video: VideoAnalysisMetadata): string {
  const transcript = compactWhitespace(video.transcriptText ?? '');
  const transcriptSection = transcript
    ? transcript.slice(0, MAX_AI_TRANSCRIPT_CHARS)
    : '未读取到公开字幕文本。请在分析中明确说明内容依据有限，只能基于页面元信息推断。';

  return `你是视频内容分析助手。请基于以下公开视频页面元信息和公开字幕，输出中文 Markdown 分析。

输出要求：
1. 使用固定标题结构：
## 视频概览
## 内容提纲
## 重点信息
## 传播/受众分析
## 可执行建议
2. 如果没有字幕文本，必须说明分析依据有限，不能假装看过完整视频。
3. 不要编造页面和字幕中没有的事实。
4. 重点信息至少 5 条；可执行建议要具体。

视频元信息：
- 来源：${video.source}
- 标题：${video.title || '未解析到标题'}
- 作者：${video.author || '未解析到作者'}
- 时长：${video.duration || '未解析到时长'}
- 发布时间：${video.publishedAt || '未解析到发布时间'}
- 原始地址：${video.originalUrl}
- 最终地址：${video.finalUrl}
- 描述：${(video.description || '无描述').slice(0, MAX_AI_DESCRIPTION_CHARS)}

清晰度：
${formatQualityList(video.qualities)}

字幕轨道：
${formatSubtitleList(video.subtitles)}

解析提示：
${video.warnings.length > 0 ? video.warnings.map(warning => `- ${warning}`).join('\n') : '- 无'}

公开字幕文本：
${transcriptSection}`;
}

export async function streamVideoAiAnalysis(options: {
  video: VideoAnalysisMetadata;
  provider?: ProviderId;
}) {
  const provider = options.provider ?? getDefaultProvider();
  const providerError = ensureProviderConfigured(provider);
  if (providerError) {
    throw new Error(providerError);
  }

  const { model, providerOptions } = getLanguageModel({
    provider,
  });

  return streamText({
    model,
    providerOptions,
    prompt: buildVideoAnalysisPrompt(options.video),
  });
}
