import { describe, expect, it } from 'vitest';

import {
  formatDateLabel,
  formatQualityLabel,
  formatSubtitleLabel,
  getTranscriptPreview,
  getVideoTitle,
  sourceLabel,
  type VideoAnalysisMetadata,
} from './video-analysis';
import { supportedVideoSourceLabel, videoSourceConfigs } from './video-analysis-sources';

describe('video-analysis helpers', () => {
  const video: VideoAnalysisMetadata = {
    source: 'youtube',
    originalUrl: 'https://www.youtube.com/watch?v=abc',
    finalUrl: 'https://www.youtube.com/watch?v=abc',
    title: '测试视频',
    qualities: [],
    subtitles: [],
    warnings: [],
  };

  it('formats source and fallback labels', () => {
    expect(sourceLabel('youtube')).toBe('YouTube');
    expect(sourceLabel('bilibili')).toBe('bilibili');
    expect(sourceLabel('douyin')).toBe('douyin');
    expect(getVideoTitle(video)).toBe('测试视频');
    expect(getVideoTitle({ ...video, title: '' })).toBe('未解析到标题');
    expect(supportedVideoSourceLabel()).toBe(videoSourceConfigs.map(config => config.label).join('、'));
  });

  it('formats dates and keeps invalid values visible', () => {
    expect(formatDateLabel('2026-04-20T00:00:00.000Z')).toContain('2026');
    expect(formatDateLabel('invalid-date')).toBe('invalid-date');
    expect(formatDateLabel()).toBe('未解析');
  });

  it('formats quality and subtitle details', () => {
    expect(
      formatQualityLabel({
        label: '720p',
        width: 1280,
        height: 720,
        fps: 30,
        mimeType: 'video/mp4',
      }),
    ).toBe('720p · 1280x720 · 30fps · video/mp4');
    expect(formatSubtitleLabel({ label: '中文', language: 'zh', isAutoGenerated: true, source: 'youtube-captions' })).toBe(
      '中文 · zh · 自动字幕 · youtube-captions',
    );
  });

  it('builds subtitle preview with empty and truncated states', () => {
    expect(getTranscriptPreview(video)).toBe('未读取到公开字幕文本。');
    expect(getTranscriptPreview({ ...video, transcriptText: '  第一段\\n第二段  ' })).toBe('第一段\\n第二段');
    expect(getTranscriptPreview({ ...video, transcriptText: 'abcdef' }, 3)).toBe('abc...');
  });
});
