import { sourceLabel, type VideoSource } from './video-analysis-sources';

export type { VideoSource };

export type VideoQualityOption = {
  label: string;
  width?: number;
  height?: number;
  fps?: number;
  bitrate?: number;
  mimeType?: string;
};

export type VideoSubtitleTrack = {
  label: string;
  language?: string;
  url?: string;
  isAutoGenerated?: boolean;
  source?: string;
};

export type VideoAnalysisMetadata = {
  source: VideoSource;
  originalUrl: string;
  finalUrl: string;
  title?: string;
  description?: string;
  thumbnailUrl?: string;
  author?: string;
  duration?: string;
  publishedAt?: string;
  qualities: VideoQualityOption[];
  subtitles: VideoSubtitleTrack[];
  transcriptText?: string;
  transcriptSource?: string;
  warnings: string[];
};

export { sourceLabel };

export function formatDateLabel(value?: string): string {
  if (!value) {
    return '未解析';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
}

export function formatQualityLabel(quality: VideoQualityOption): string {
  const details = [
    quality.width && quality.height ? `${quality.width}x${quality.height}` : null,
    quality.fps ? `${quality.fps}fps` : null,
    quality.mimeType,
  ].filter(Boolean);

  return details.length > 0 ? `${quality.label} · ${details.join(' · ')}` : quality.label;
}

export function formatSubtitleLabel(subtitle: VideoSubtitleTrack): string {
  const details = [
    subtitle.language,
    subtitle.isAutoGenerated ? '自动字幕' : null,
    subtitle.source,
  ].filter(Boolean);

  return details.length > 0 ? `${subtitle.label} · ${details.join(' · ')}` : subtitle.label;
}

export function getTranscriptPreview(video: VideoAnalysisMetadata, maxLength = 800): string {
  const text = video.transcriptText?.replace(/\s+/g, ' ').trim() ?? '';
  if (!text) {
    return '未读取到公开字幕文本。';
  }

  if (text.length <= maxLength) {
    return text;
  }

  return `${text.slice(0, maxLength)}...`;
}

export function getVideoTitle(video: VideoAnalysisMetadata): string {
  return video.title?.trim() || '未解析到标题';
}
